#!/usr/bin/env bash
# Example mTLS calls against a local lipd-server.
# Requires dev certs generated by `make certs` into ./tls.
set -euo pipefail
BASE="https://localhost:8443/api/v1"
MTLS=(--cacert tls/ca.crt --cert tls/client.crt --key tls/client.key)

echo "== health =="
curl -s "${MTLS[@]}" "$BASE/health"; echo

echo "== register node =="
REG=$(curl -s "${MTLS[@]}" -X POST "$BASE/register" \
  -H 'Content-Type: application/json' \
  -d '{"customer_id":"11111111-1111-1111-1111-111111111111","initial_secret":"dev"}')
echo "$REG"
TOKEN=$(echo "$REG" | sed -n 's/.*"token":"\([^"]*\)".*/\1/p')

echo "== get policies =="
curl -s "${MTLS[@]}" -H "Authorization: Bearer $TOKEN" \
  "$BASE/policies?customer_id=11111111-1111-1111-1111-111111111111"; echo

echo "== log a decision =="
curl -s "${MTLS[@]}" -X POST "$BASE/audit/log" \
  -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
  -d '{"customer_id":"11111111-1111-1111-1111-111111111111","event_type":"flowspec_drop","detail":{"rule":"rf-2019"}}'; echo
